name : CI
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: '7.9.2'
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --prefer-offline --frozen-lockfile 
      - run: pnpm playwright install chromium
      - run: pnpm run ci
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_PROJECT_ID: ${{ secrets.TURBO_PROJECT_ID }}
