name : CI
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: '7.9.2'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm config set registry https://registry.npmjs.org/
      - run: pnpm store prune          
      - run: |
          if [ ! -f pnpm-lock.yaml ]; then
            echo "pnpm-lock.yaml not found, generating it."
            pnpm install --lockfile-only
          fi
      - run: pnpm install
      - run: pnpm playwright install chromium
      - run: pnpm run ci
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_PROJECT_ID: ${{ secrets.TURBO_PROJECT_ID }}
